import os, re
for i in range(15, 31):
    tex_path = f"lecture_{i}.tex"
    if not os.path.exists(tex_path): continue
    with open(tex_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    images_in_tex = re.findall(r"\\includegraphics.*?\{(.*?)\}", content)
    print(f"Lecture {i}:")
    print("  In tex:", images_in_tex)
    
    py_script = f"generate_lecture_{i}_images.py"
    if os.path.exists(py_script):
        with open(py_script, "r", encoding="utf-8") as f:
            py_content = f.read()
            images_in_py = re.findall(r"plt\.savefig\(['\"](.*?)['\"]", py_content)
            print("  Generated by py:", images_in_py)
